name: build-test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: "2.2.108"
    - run: dotnet test tests
    - run: dotnet test example-order-integration/tests
